#!/bin/sh
# 모니터링 서버에 샘플 로그를 보낸다. 사용: ./scripts/send-sample.sh [http://localhost:8081]
URL="${1:-http://localhost:8081}/ingest"
NOW=$(($(date +%s) * 1000))
RID="sample-$(date +%s)"

curl -s -X POST "$URL" -H 'Content-Type: application/json' -d '[
{"requestId":"'"$RID"'-1","serviceName":"sample-api","method":"GET","path":"/api/v1/reports?page=0","requestHeaders":{"authorization":"****","accept":"application/json"},"statusCode":200,"responseHeaders":{"content-type":"application/json"},"responseBody":"{\"success\":true,\"data\":{\"items\":[{\"id\":1,\"title\":\"8월 월간 보고서\"}]}}","durationMs":42,"clientIp":"10.0.0.5","timestamp":'"$NOW"'},
{"requestId":"'"$RID"'-2","serviceName":"sample-api","method":"POST","path":"/api/v1/auth/login","requestHeaders":{"content-type":"application/json"},"requestBody":"{\"loginId\":\"admin\",\"password\":\"****\"}","statusCode":401,"responseBody":"{\"success\":false,\"message\":\"비밀번호가 일치하지 않습니다.\"}","durationMs":88,"clientIp":"10.0.0.7","timestamp":'"$NOW"',"exception":{"exceptionClass":"com.example.auth.domain.InvalidPasswordException","message":"비밀번호가 일치하지 않습니다.","handled":true,"stackTrace":"com.example.auth.domain.InvalidPasswordException: 비밀번호가 일치하지 않습니다.\n\tat com.example.auth.application.AuthService.login(AuthService.java:52)\n\tat com.example.auth.web.AuthController.login(AuthController.java:31)"}},
{"requestId":"'"$RID"'-3","serviceName":"sample-api","method":"POST","path":"/api/v1/reports","requestHeaders":{"content-type":"application/json"},"requestBody":"{\"agentId\":\"A-100\",\"month\":\"2026-08-01\"}","statusCode":500,"responseBody":"{\"success\":false,\"message\":\"서버 내부 오류가 발생했습니다.\"}","durationMs":1204,"clientIp":"10.0.0.5","timestamp":'"$NOW"',"exception":{"exceptionClass":"org.springframework.dao.DataIntegrityViolationException","message":"could not execute statement","handled":true,"stackTrace":"org.springframework.dao.DataIntegrityViolationException: could not execute statement\n\tat org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:290)\n\tat com.example.report.application.ReportService.create(ReportService.java:77)\n\tat com.example.report.web.ReportController.create(ReportController.java:40)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:258)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:903)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:139)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: org.hibernate.exception.ConstraintViolationException: could not execute statement\n\t... 42 more\nCaused by: java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row\n\t... 50 more","cause":{"exceptionClass":"org.hibernate.exception.ConstraintViolationException","message":"could not execute statement","cause":{"exceptionClass":"java.sql.SQLIntegrityConstraintViolationException","message":"Cannot add or update a child row: a foreign key constraint fails"}}}},
{"kind":"OUTBOUND","requestId":"'"$RID"'-4a","parentRequestId":"'"$RID"'-4","serviceName":"sample-api","method":"POST","targetHost":"ai-server:8000","path":"/query","requestHeaders":{"x-api-key":"****","x-request-id":"'"$RID"'-4"},"requestBody":"{\"message\":\"이번 달 위험 기관 알려줘\"}","statusCode":200,"responseHeaders":{"content-type":"text/event-stream"},"responseBody":"event: token\ndata: {\"text\":\"이번 달\"}\n\nevent: done\ndata: {}\n","durationMs":3180,"timestamp":'"$NOW"'},
{"requestId":"'"$RID"'-4","serviceName":"sample-api","method":"POST","path":"/api/v1/chat-sessions","requestBody":"{\"message\":\"이번 달 위험 기관 알려줘\"}","statusCode":200,"responseHeaders":{"content-type":"text/event-stream"},"responseBody":"event: token\ndata: {\"text\":\"이번 달\"}\n\n","durationMs":3260,"async":true,"clientIp":"10.0.0.9","timestamp":'"$NOW"'},
{"kind":"OUTBOUND","requestId":"'"$RID"'-5","serviceName":"sample-api","method":"GET","targetHost":"partner-gw:9000","path":"/export/123/status","statusCode":null,"durationMs":5002,"timestamp":'"$NOW"',"exception":{"exceptionClass":"java.net.SocketTimeoutException","message":"Read timed out","stackTrace":"java.net.SocketTimeoutException: Read timed out\n\tat java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278)"}}
]'
echo
